version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - es-net
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    networks:
      - es-net
    links:
      - zookeeper
    ports:
      - 19092:9092
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
#      KAFKA_NUM_PARTITIONS: 1
#      KAFKA_CREATE_TOPICS: "topic-getting-things-done:5:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#  discovery:
#    image: getting-things-done/discovery-service
#    ports:
#     - "8761:8761"
#    environment:
#      eureka.instance.hostname: discovery
#  gateway:
#    image: getting-things-done/api-gateway
#    links:
#      - discovery
#      - gtd-command-side
#      - gtd-query-side
#    ports:
#      - "8765:8765"
#    environment:
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
  command:
    image: getting-things-done/command
    networks:
      - es-net
#    links:
#      - discovery
    ports:
     - "8090:8090"
    environment:
      SERVER_PORT: 8090
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092
  query:
    image: getting-things-done/query
    networks:
      - es-net
#    links:
#      - discovery
    ports:
     - "8089:8089"
    environment:
      SERVER_PORT: 8089
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/

networks:
  es-net:
    driver: bridge